server:
  port: 8080
  servlet:
    context-path: /fin-flow


spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/fin-flow"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#jwt:
#  signerKey: "DhKR6cRqvlRkWqvobvP2kI1/b+F9DTATJCu5mvbroqHl9YneS7gI+b/77KBGl7za"
#  valid-duration: 3600
#  refreshable-duration: 36000