server:
  port: 8080
  servlet:
    context-path: /fin-flow

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/fin_flow"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: ${FINFLOW_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false

outbound:
  identity:
    client-id: ${FINFLOW_GOOGLE_CLIENT_ID}
    client-secret: ${FINFLOW_GOOGLE_CLIENT_SECRET}
    redirect-uri: "http://localhost:3000/authenticate"

jwt:
  signerKey: ${FINFLOW_JWTSIGNERKEY}
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

pageable:
  size: 3
